##
# these scripts set up a simple web application stack with a configured
# server
#
---

- name: ensure web server packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - fail2ban
    - git
    - python-dev
    - python-virtualenv
    - supervisor

- name: clone or pull latest web app code
  git: repo={{code_repository}} dest={{app_code_dir}}
       accept_hostkey=yes version=master

- name: check if virtualenv already exists
  stat: path={{virtualenv_dir}}
  register: venv_dir

- name: create virtualenv for web application
  shell: virtualenv {{virtualenv_dir}}
  when: venv_dir.stat.isdir is not defined

- name: install web application dependencies listed in requirements.txt
  pip: requirements={{app_code_dir}}/requirements.txt
       virtualenv={{virtualenv_dir}}

- name: write setenvs.sh environment variables
  template: src=setenvs.sh.j2 dest={{ app_code_dir }}/setenvs.sh

- name: check if supervisor.sock exists
  stat: path=/var/run/supervisor.sock
  register: supervisor_sock_file

- name: delete supervisor.sock file so supervisor can start
  command: rm /var/run/supervisor.sock
  sudo: yes
  when: supervisor_sock_file.stat.exists

- name: write supervisor configuration for web application
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/{{app_name}}.conf
  sudo: yes
  notify:
    - restart supervisor

- name: notify deployer that the application is ready to roll
  local_action: twilio account_sid={{twilio_account_sid}}
  
